apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: buildah-
spec:
  pipelineRef:
    name: buildah
  serviceAccountName: build-robot
  workspaces:
  - name: pipeline-shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce 
        resources:
          requests:
            storage: 1Gi
