apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: build-robot
rules:
- apiGroups: [""] 
  resources: ["services"]
  verbs: ["get", "create"]
- apiGroups: ["apps"] 
  resources: ["deployments"]
  verbs: ["get", "create", "list"]
- apiGroups: ["route.openshift.io"] 
  resources: ["routes"]
  verbs: ["get", "create"]